version: '3.7'

services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
    networks:
      kafka:
        aliases:
          - zookeeper1

  zookeeper2:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_SERVER_ID=2
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
    networks:
      kafka:
        aliases:
          - zookeeper2

  zookeeper3:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_SERVER_ID=3
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
    networks:
      kafka:
        aliases:
          - zookeeper3

  kafka1:
    container_name: kafka1
    image: confluentinc/cp-kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL_DOCKER_LISTENER://kafka1:29092, EXTERNAL_LISTENER://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL_DOCKER_LISTENER:PLAINTEXT,EXTERNAL_LISTENER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL_DOCKER_LISTENER
      - CONFLUENT_SUPPORT_METRICS_ENABLE=0
    networks:
      kafka:
        aliases:
          - kafka1
    depends_on: 
      - zookeeper1
      - zookeeper2
      - zookeeper3

  kafka2:
    image: confluentinc/cp-kafka:latest
    ports:
      - 9093:9093
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL_DOCKER_LISTENER://kafka2:29092, EXTERNAL_LISTENER://localhost:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL_DOCKER_LISTENER:PLAINTEXT,EXTERNAL_LISTENER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL_DOCKER_LISTENER
      - CONFLUENT_SUPPORT_METRICS_ENABLE=0
    networks:
      kafka:
        aliases:
          - kafka2
    depends_on: 
      - zookeeper1
      - zookeeper2
      - zookeeper3

  kafka3:
    image: confluentinc/cp-kafka:latest
    ports:
      - 9094:9094
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL_DOCKER_LISTENER://kafka3:29092, EXTERNAL_LISTENER://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL_DOCKER_LISTENER:PLAINTEXT,EXTERNAL_LISTENER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL_DOCKER_LISTENER
      - CONFLUENT_SUPPORT_METRICS_ENABLE=0
    networks:
      kafka:
        aliases:
          - kafka3
    depends_on: 
      - zookeeper1
      - zookeeper2
      - zookeeper3
  
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - 9000:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka1:29092,kafka2:29092,kafka3:29092
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      kafka:

networks:
  kafka: